typography_spectrum: 0.26314992900006473
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.625
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74875
analytics:
  google: null
  facebook: null
  twitter: null
name: John Random
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
